# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: NokiaSros1!   # SR-SIM credentials changed to admin/NokiaSros1! (vSIM were admin/admin)
# skip-verify: true
insecure: true
port: 57400
timeout: 10s
encoding: json_ietf

targets:
  pe1:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_anysec_peer
      - sros_anysec_encryption_group
      - sros_anysec_peer_config
      - sros_anysec_sec_termination_policy
      - sros_anysec_mka_over_ip
      - sros_macsec_config
      - sros_macsec_if_stats
      - sros_macsec_connectivity_association
      - sros_epipe_instance_oper_state
      - sros_vpls_instance_oper_state
      - sros_vprn_instance_oper_state
  pe2:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_anysec_peer
      - sros_anysec_encryption_group
      - sros_anysec_peer_config
      - sros_anysec_sec_termination_policy
      - sros_anysec_mka_over_ip
      - sros_macsec_config
      - sros_macsec_if_stats
      - sros_macsec_connectivity_association
      - sros_epipe_instance_oper_state
      - sros_vpls_instance_oper_state
      - sros_vprn_instance_oper_state
  p3:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
  p4:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats

  ce5:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_macsec_config
      - sros_macsec_if_stats
      - sros_macsec_connectivity_association
      - sros_epipe_instance_oper_state

  ce6:57400:
    subscriptions:
      - sros_port_oper_state
      - sros_port_stats
      - sros_port_traffic_rate
      - sros_if_stats
      - sros_macsec_config
      - sros_macsec_if_stats
      - sros_macsec_connectivity_association
      - sros_epipe_instance_oper_state

subscriptions:
  sros_port_oper_state:
    paths:
      - /state/port[port-id=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_port_stats:
    paths:
      - /state/port[port-id=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_port_traffic_rate:
    paths:
      - /state/port[port-id=*]/ethernet/oper-speed
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_if_stats:
    paths:
      - /state/router[router-name=Base]/interface[interface-name=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_anysec_peer:
    paths:
      - /state/anysec/tunnel-encryption/encryption-group[group-name=*]/peer[peer-ip-address=*]
    mode: stream
    stream-mode: target-defined
    sample-interval: 2s

  sros_anysec_encryption_group:
    paths:
      - /configure/anysec/tunnel-encryption/encryption-group[group-name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_anysec_peer_config:
    paths:
      - /configure/anysec/tunnel-encryption/encryption-group[group-name=*]/peer[peer-ip-address=*]
    mode: stream
    stream-mode: target-defined
    sample-interval: 2s

  sros_anysec_sec_termination_policy:
    paths:
      - /state/anysec/tunnel-encryption/security-termination-policy[policy-name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_anysec_mka_over_ip:
    paths:
      - /configure/anysec/mka-over-ip
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_macsec_config:
    paths:
      - /configure/macsec
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_macsec_if_stats:
    paths:
      - /state/port[port-id=*]/ethernet/dot1x/macsec/sub-port/statistics
    mode: stream
    stream-mode: target-defined
    sample-interval: 2s

  sros_macsec_connectivity_association:
    paths:
      - /configure/macsec/connectivity-association[ca-name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_epipe_instance_oper_state:
    paths:
      - /state/service/epipe[service-name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_vpls_instance_oper_state:
    paths:
      - /state/service/vpls[service-name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 2s

  sros_vprn_instance_oper_state:
    paths:
      - /state/service/vprn[service-name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 2s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  up-down-map:
    event-strings:
      value-names:
        - oper-state
        - admin-state
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
        - replace:
            apply-on: "value"
            old: "enable"
            new: "1"
        - replace:
            apply-on: "value"
            old: "disable"
            new: "0"
